"""
Brandflow AI - Analytics Pydantic Schemas
==========================================
Response models for all analytics and monitoring API endpoints.

These schemas define exactly what the frontend receives.
They are designed to be frontend-friendly and graph-ready.

Schemas:
    AnalyticsOverviewResponse   — Master dashboard summary card
    PostStatsResponse           — Post counts broken down by status
    GenerationAnalyticsResponse — AI generation usage metrics
    PublishStatsResponse        — Publishing success rates + history
    WorkerHealthResponse        — Celery task execution metrics
    UserActivityResponse        — Paginated activity feed
    RecentActivityItem          — Single activity event item
    PublishLogItem              — Single publish history entry
    WorkerLogItem               — Single worker task entry
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Shared / Primitive Models
# ---------------------------------------------------------------------------

class RecentActivityItem(BaseModel):
    """
    A single item in the user activity feed.
    Designed for the frontend dashboard's 'Recent Activity' panel.
    """
    id: Optional[str] = None
    event_type: str = Field(..., description="ActivityEventType constant string")
    title: str = Field(..., description="Human-readable event title")
    description: str = Field(default="", description="Short context subtitle")
    post_id: Optional[str] = None
    schedule_id: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime


class PublishLogItem(BaseModel):
    """
    A single entry in the publish history list.
    """
    id: Optional[str] = None
    post_id: str
    schedule_id: str
    platform: str = "instagram"
    status: str                            # "success" | "failed"
    instagram_post_id: Optional[str] = None
    error_message: Optional[str] = None
    execution_time_ms: Optional[int] = None
    published_at: Optional[datetime] = None
    created_at: datetime


class WorkerLogItem(BaseModel):
    """
    A single Celery task execution record.
    """
    id: Optional[str] = None
    task_name: str
    post_id: Optional[str] = None
    schedule_id: Optional[str] = None
    status: str                            # "success" | "failed" | "retried" | "skipped"
    retry_count: int = 0
    error_message: Optional[str] = None
    execution_time_ms: Optional[int] = None
    executed_at: datetime


class GenerationLogItem(BaseModel):
    """
    A single AI generation log entry.
    """
    id: Optional[str] = None
    post_id: Optional[str] = None
    prompt: str = ""
    status: str                            # "success" | "failed"
    duration_ms: Optional[int] = None
    model: str = ""
    error_message: Optional[str] = None
    created_at: datetime


# ---------------------------------------------------------------------------
# Overview / Dashboard Summary
# ---------------------------------------------------------------------------

class AnalyticsOverviewData(BaseModel):
    """Core data payload for the overview endpoint."""
    # Post lifecycle counts
    total_posts: int = Field(0, description="Total posts ever created by this user")
    draft_posts: int = Field(0, description="Posts still in draft state")
    scheduled_posts: int = Field(0, description="Posts currently scheduled")
    published_posts: int = Field(0, description="Successfully published posts")
    failed_posts: int = Field(0, description="Posts that failed to publish")
    cancelled_posts: int = Field(0, description="Cancelled scheduled posts")

    # AI & automation stats
    total_ai_generations: int = Field(0, description="Total AI content generation events")
    total_automations_executed: int = Field(0, description="Total Celery tasks executed")
    total_images_generated: int = Field(0, description="Total images generated by AI")

    # Publishing stats
    total_publish_attempts: int = Field(0, description="Total Instagram publish attempts")
    successful_publishes: int = Field(0, description="Successful Instagram publishes")
    failed_publishes: int = Field(0, description="Failed Instagram publish attempts")
    publishing_success_rate: float = Field(
        0.0, description="Percentage of successful publishes (0-100)"
    )

    # Account state
    instagram_connected: bool = Field(False, description="Whether IG is currently connected")

    # Period
    period_days: int = Field(30, description="Analytics window in days")


class AnalyticsOverviewResponse(BaseModel):
    """Response envelope for GET /analytics/overview."""
    success: bool = True
    data: AnalyticsOverviewData


# ---------------------------------------------------------------------------
# Post Statistics
# ---------------------------------------------------------------------------

class PostStatusBreakdown(BaseModel):
    """Post counts broken down by each status value."""
    draft: int = 0
    scheduled: int = 0
    published: int = 0
    failed: int = 0
    cancelled: int = 0
    publishing: int = 0
    executed: int = 0
    ready: int = 0


class PostStatsData(BaseModel):
    """Post statistics data payload."""
    total: int = Field(0, description="Total posts")
    by_status: PostStatusBreakdown = Field(
        default_factory=PostStatusBreakdown,
        description="Post count grouped by status"
    )
    # Time trend — list of {date: 'YYYY-MM-DD', count: N} for chart rendering
    daily_trend: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Daily post creation counts for the last 30 days (graph-ready)"
    )
    most_used_tone: Optional[str] = None
    most_used_style: Optional[str] = None


class PostStatsResponse(BaseModel):
    """Response envelope for GET /analytics/posts."""
    success: bool = True
    data: PostStatsData


# ---------------------------------------------------------------------------
# AI Generation Analytics
# ---------------------------------------------------------------------------

class GenerationAnalyticsData(BaseModel):
    """AI generation statistics payload."""
    total_generations: int = 0
    successful_generations: int = 0
    failed_generations: int = 0
    success_rate: float = 0.0          # percentage
    avg_duration_ms: Optional[float] = None
    most_used_model: Optional[str] = None
    # Daily trend list [{date, count}]
    daily_trend: List[Dict[str, Any]] = Field(default_factory=list)
    # Most recent generation logs
    recent_logs: List[GenerationLogItem] = Field(default_factory=list)


class GenerationAnalyticsResponse(BaseModel):
    """Response envelope for GET /analytics/generations."""
    success: bool = True
    data: GenerationAnalyticsData


# ---------------------------------------------------------------------------
# Publishing Statistics
# ---------------------------------------------------------------------------

class PublishStatsData(BaseModel):
    """Instagram publishing statistics payload."""
    total_attempts: int = 0
    successful_publishes: int = 0
    failed_publishes: int = 0
    success_rate: float = 0.0          # percentage
    avg_execution_time_ms: Optional[float] = None
    # Daily publish trend [{date, success_count, fail_count}]
    daily_trend: List[Dict[str, Any]] = Field(default_factory=list)
    # Most recent publish records (for the history table)
    recent_history: List[PublishLogItem] = Field(default_factory=list)


class PublishStatsResponse(BaseModel):
    """Response envelope for GET /analytics/publishing."""
    success: bool = True
    data: PublishStatsData


# ---------------------------------------------------------------------------
# Worker / Celery Health
# ---------------------------------------------------------------------------

class WorkerHealthData(BaseModel):
    """Celery task execution health metrics."""
    total_tasks_executed: int = 0
    successful_tasks: int = 0
    failed_tasks: int = 0
    retried_tasks: int = 0
    skipped_tasks: int = 0
    success_rate: float = 0.0          # percentage
    avg_execution_time_ms: Optional[float] = None
    # Most recent task executions
    recent_executions: List[WorkerLogItem] = Field(default_factory=list)


class WorkerHealthResponse(BaseModel):
    """Response envelope for GET /analytics/workers."""
    success: bool = True
    data: WorkerHealthData


# ---------------------------------------------------------------------------
# User Activity Feed
# ---------------------------------------------------------------------------

class UserActivityResponse(BaseModel):
    """Response envelope for GET /analytics/activity."""
    success: bool = True
    count: int = 0
    data: List[RecentActivityItem] = Field(default_factory=list)
