"""
Brandflow AI - Post Pydantic Schemas
=======================================
These schemas define the shape of data flowing into and out of the API layer
for all post-related endpoints.

They are deliberately separate from the MongoDB model (PostDocument) to give
full control over what is exposed vs. what is stored.

Schema hierarchy:
    PostCreate      — API input for POST /posts
    PostUpdate      — API input for PUT /posts/{id}  (all fields optional)
    PostResponse    — API output (safe to return, no internal fields)

Generic wrappers (shared with auth):
    SuccessResponse — { success, message, data }
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Valid choice constants (for field validators)
# ---------------------------------------------------------------------------
VALID_STATUSES       = {"draft", "scheduled", "published"}
VALID_DESIGN_STYLES  = {"luxury", "minimal", "startup", "bold", "elegant", "modern", "retro"}
VALID_TONES          = {"viral", "professional", "educational", "humorous", "inspirational", "casual"}


# ---------------------------------------------------------------------------
# Input Schema — POST /posts
# ---------------------------------------------------------------------------
class PostCreate(BaseModel):
    """
    Schema for creating a new post.
    Only 'prompt' is strictly required — all other fields have sensible defaults.
    Caption/hashtags can be pre-populated by the AI layer (future phase) or
    supplied directly by the user.
    """

    prompt: str = Field(
        ...,
        min_length=5,
        max_length=2000,
        description="AI generation prompt or content brief",
        examples=["A luxury watch brand post for Instagram targeting professionals"],
    )
    caption: str = Field(
        default="",
        max_length=2200,  # Instagram caption limit
        description="Post caption (generated by AI or written manually)",
        examples=["Precision meets elegance. ⌚ #LuxuryWatch"],
    )
    hashtags: List[str] = Field(
        default_factory=list,
        description="List of hashtags (without '#' prefix)",
        examples=[["luxury", "watch", "style"]],
    )
    design_style: str = Field(
        default="",
        max_length=50,
        description="Visual design style: luxury | minimal | startup | bold | elegant | modern | retro",
        examples=["luxury"],
    )
    tone: str = Field(
        default="",
        max_length=50,
        description="Content tone: viral | professional | educational | humorous | inspirational | casual",
        examples=["professional"],
    )
    image_url: Optional[str] = Field(
        default=None,
        max_length=2048,
        description="S3/CDN URL of the post image (set by the image generation pipeline)",
    )
    scheduled_time: Optional[datetime] = Field(
        default=None,
        description="UTC datetime when the post should be auto-published",
    )

    @field_validator("design_style")
    @classmethod
    def validate_design_style(cls, v: str) -> str:
        """Accept empty string (means 'not set') or a known style value."""
        if v and v.lower() not in VALID_DESIGN_STYLES:
            raise ValueError(
                f"design_style must be one of: {', '.join(sorted(VALID_DESIGN_STYLES))}. Got '{v}'."
            )
        return v.lower() if v else v

    @field_validator("tone")
    @classmethod
    def validate_tone(cls, v: str) -> str:
        """Accept empty string (means 'not set') or a known tone value."""
        if v and v.lower() not in VALID_TONES:
            raise ValueError(
                f"tone must be one of: {', '.join(sorted(VALID_TONES))}. Got '{v}'."
            )
        return v.lower() if v else v

    @field_validator("hashtags")
    @classmethod
    def clean_hashtags(cls, v: List[str]) -> List[str]:
        """
        Strip leading '#' characters and whitespace from each hashtag.
        Also removes duplicates while preserving order.
        """
        seen: set = set()
        cleaned: List[str] = []
        for tag in v:
            tag = tag.strip().lstrip("#").lower()
            if tag and tag not in seen:
                seen.add(tag)
                cleaned.append(tag)
        return cleaned


# ---------------------------------------------------------------------------
# Input Schema — PUT /posts/{id}
# ---------------------------------------------------------------------------
class PostUpdate(BaseModel):
    """
    Schema for updating an existing post.
    Every field is Optional — the client only sends the fields it wants to change.
    The service layer will merge non-None values into the existing document.
    """

    prompt: Optional[str] = Field(
        default=None,
        min_length=5,
        max_length=2000,
        description="Revised AI prompt",
    )
    caption: Optional[str] = Field(
        default=None,
        max_length=2200,
        description="Updated caption text",
    )
    hashtags: Optional[List[str]] = Field(
        default=None,
        description="Replacement hashtag list (replaces entirely, not appended)",
    )
    design_style: Optional[str] = Field(
        default=None,
        max_length=50,
        description="Updated design style",
    )
    tone: Optional[str] = Field(
        default=None,
        max_length=50,
        description="Updated content tone",
    )
    status: Optional[str] = Field(
        default=None,
        description="Post workflow status: draft | scheduled | published",
    )
    image_url: Optional[str] = Field(
        default=None,
        max_length=2048,
        description="Updated image URL",
    )
    scheduled_time: Optional[datetime] = Field(
        default=None,
        description="Updated scheduled publish time (UTC)",
    )

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v.lower() not in VALID_STATUSES:
            raise ValueError(
                f"status must be one of: {', '.join(sorted(VALID_STATUSES))}. Got '{v}'."
            )
        return v.lower() if v else v

    @field_validator("design_style")
    @classmethod
    def validate_design_style(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v.lower() not in VALID_DESIGN_STYLES:
            raise ValueError(
                f"design_style must be one of: {', '.join(sorted(VALID_DESIGN_STYLES))}. Got '{v}'."
            )
        return v.lower() if v else v

    @field_validator("tone")
    @classmethod
    def validate_tone(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v.lower() not in VALID_TONES:
            raise ValueError(
                f"tone must be one of: {', '.join(sorted(VALID_TONES))}. Got '{v}'."
            )
        return v.lower() if v else v

    @field_validator("hashtags")
    @classmethod
    def clean_hashtags(cls, v: Optional[List[str]]) -> Optional[List[str]]:
        if v is None:
            return None
        seen: set = set()
        cleaned: List[str] = []
        for tag in v:
            tag = tag.strip().lstrip("#").lower()
            if tag and tag not in seen:
                seen.add(tag)
                cleaned.append(tag)
        return cleaned


# ---------------------------------------------------------------------------
# Output Schema — API responses
# ---------------------------------------------------------------------------
class PostResponse(BaseModel):
    """
    Safe public representation of a Post document.
    Excludes internal MongoDB fields and serialises ObjectId as plain string.
    """

    id: str = Field(..., description="Post MongoDB document ID as string")
    user_id: str = Field(..., description="Owner's user ID")

    # Content
    prompt: str
    caption: str
    hashtags: List[str]

    # Style
    design_style: str
    tone: str

    # Workflow
    status: str
    image_url: Optional[str]
    scheduled_time: Optional[datetime]

    # Timestamps
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Generic API Response Wrappers for Posts
# ---------------------------------------------------------------------------
class PostSuccessResponse(BaseModel):
    """
    Standard envelope for single-post mutation responses.

    Example:
        {
            "success": true,
            "message": "Post created successfully",
            "data": { ...post fields... }
        }
    """

    success: bool = True
    message: str
    data: PostResponse


class PostListResponse(BaseModel):
    """
    Standard envelope for list responses.

    Example:
        {
            "success": true,
            "message": "Posts retrieved successfully",
            "count": 3,
            "data": [ ...posts... ]
        }
    """

    success: bool = True
    message: str
    count: int
    data: List[PostResponse]


class DeleteResponse(BaseModel):
    """Minimal response for successful delete operations."""

    success: bool = True
    message: str
    deleted_id: str
